version: 2

aliases:
  - &defaults
    working_directory: ~/app
    docker:
      # specify the version you desire here
      - image: tomnewton/lot-tracker-build:latest

  - &init-gcloud-dev
    run:
      name: Prep gcloud
      command: |
        echo $GCLOUD_SERVICE_KEY_DEV > ${HOME}/gcloud-service-key.json
        gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
        gcloud config set project ${GCLOUD_PROJECT_DEV}
        gcloud auth configure-docker --quiet
        gcloud info

  - &init-gcloud-production
    run: 
      name: Prep gcloud production
      command: | 
        echo $GOOGLE_SERVICE_KEY_PRODUCTION > ${HOME}/gcloud-service-key.json
        gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
        gcloud config set project ${GOOGLE_PROJECT_PRODUCTION}
        gcloud auth configure-docker --quiet
        gcloud info
        sed -i "s/REPLACE_SHOPIFY_SECRET/$SHOPIFY_SECRET_PRODUCTION/g" services/default/app.yaml

  - &generate-and-set-version-env
    run: 
      name: Generate & set version
      command: |
        echo 'export VERSION=${CIRCLE_TAG//\./-}' >> $BASH_ENV
        source $BASH_ENV

  - &update-gcloud-components 
    run:
      name: update gcloud components 
      command: |
        apt-get update

  - &yarn-init
    run:
      name: yarn init
      command: |
        yarn config set workspaces-experimental true
        yarn install --frozen-lockfile --production

  - &run-tests
    run: 
      name: run tests
      command: |
        cd services/default/ && yarn test
jobs:
  lot-tracker-build:
    <<: *defaults
    steps:
      - checkout
      - *update-gcloud-components
      - *init-gcloud-production
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "services/default/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - *yarn-init
      - run: cd services/default/ && yarn build
      - *run-tests
    
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "services/default/package.json" }}
      
      - run: cd services/default/ && gcloud app deploy


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - lot-tracker-build:
          filters:
            branches:
              only: master
