runtime: nodejs10
instance_class: F1

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  SHOPIFY_SECRET: REPLACE_SHOPIFY_SECRET
  GOOGLE_CLIENT_SECRET: REPLACE_GOOGLE_CLIENT_SECRET
  SESSION_SECRET: REPLACE_SESSION_SECRET