runtime: nodejs10
instance_class: F1

handlers:
- url: /manifest\.json
  static_files: manifest.json
  upload: dist/client/build/manifest\.json

- url: /favicon\.ico
  static_files: favicon.ico
  upload: dist/client/build/favicon\.ico

- url: /static
  static_dir: dist/client/build/static

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  SHOPIFY_SECRET: REPLACE_SHOPIFY_SECRET
  GOOGLE_CLIENT_SECRET: REPLACE_GOOGLE_CLIENT_SECRET
  SESSION_SECRET: REPLACE_SESSION_SECRET